# .streamlit/secrets.toml
SUPABASE_URL = "https://ovmwkpogwcayuuzablxx.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92bXdrcG9nd2NheXV1emFibHh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2NjM1MTMsImV4cCI6MjA4NjIzOTUxM30.B09UcZCknGyAi_RQgvs-PgLIFnsUuKy8m8FZVxMpxWw"